name: lock_orientation_screen
description: "Lock Orientation Screen is a Flutter package designed to help developers easily lock the screen orientation to portrait mode within their applications. This package simplifies the process by managing the system's orientation settings seamlessly"
version: 0.0.1
repository: https://github.com/mohamedmagdy2301/lock_orientation_screen

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:
